module Context.Throw.IO
  (
  )
where

-- import qualified Context.Throw as Throw
-- import qualified Control.Exception.Safe as Safe

-- new :: Throw.Config -> IO Throw.Context
-- new _ =
--   return
--     Throw.Context
--       { Throw.throw = Safe.throw,
--         Throw.try = Safe.try
--       }
